// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnMA1HAEM1JtqD9IVf1ju1ViVcA1f7K9w',
    appId: '1:335496529374:web:9e40fe2dad61b5be96094f',
    messagingSenderId: '335496529374',
    projectId: 'bloc-login-firebase',
    authDomain: 'bloc-login-firebase.firebaseapp.com',
    storageBucket: 'bloc-login-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeV3NklsrY3ehwTpeomFgzR3xWEFUf74Q',
    appId: '1:335496529374:ios:aa653d13fa577f1096094f',
    messagingSenderId: '335496529374',
    projectId: 'bloc-login-firebase',
    storageBucket: 'bloc-login-firebase.appspot.com',
    iosClientId: '335496529374-08mj44s107tc4mghtif6lc23omqo1nel.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeV3NklsrY3ehwTpeomFgzR3xWEFUf74Q',
    appId: '1:335496529374:ios:aa653d13fa577f1096094f',
    messagingSenderId: '335496529374',
    projectId: 'bloc-login-firebase',
    storageBucket: 'bloc-login-firebase.appspot.com',
    iosClientId: '335496529374-08mj44s107tc4mghtif6lc23omqo1nel.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );
}
